### ISSUE TITLE
Develop the bundle closure algorithm

### ISSUE THREAD

**Issue by StevenJenkinsJPL** [opencaesar/owl-adapter#4]
## User Story
As a  developer, I would like the OWL generated from my bundle terminologies to include disjointness axioms so that an OWL reasoner can find errors caused by vocabulary misuse.

## Detailed Description
The bundle closure algorithm should generate the smallest set of disjointness axioms that satisfies the policy that any two classes that do not share a common explicit subclass are disjoint.

## Tasks
- [ ] query an OML bundle for its specialization axioms
- [ ] construct the taxonomy
- [ ] invoke the utilities to treeify it
- [ ] express the resulting implied disjointness as OWL axioms.
